 <div class="vc-custom-col-spacing clearfix vc-col-spacing-30"><section class="wpb_row vc_row-fluid"><div class="ambersix-container"><div class="row-inner clearfix"><div class="wpb_column vc_column_container vc_col-sm-12"><div class="vc_column-inner"><div class="wpb_wrapper">
                                                                <div class="ambersix-spacer clearfix" data-desktop="40" data-mobi="30" data-smobi="30"></div><div class="ambersix-headings clearfix text-center wow fadeInUp" data-font=38 data-wow-duration="0.75s" data-wow-delay="0.3s"><h2 class="heading clearfix" style="color:#1f2041;line-height:50px;font-size:38px;">
                                                                        Our Recent Projects
                                                                    </h2></div>
                                                                <div class="ambersix-spacer clearfix" data-desktop="40" data-mobi="60" data-smobi="60"></div>
                                                                <div class="ambersix-project-grid" data-layout="masonry" data-column="3" data-column2="3" data-column3="2" data-column4="1" data-gaph="50" data-gapv="30" data-filter="">
                                                                    <div>

                                                                        <div id="project-filter" class="cbp-l-filters-alignCenter clearfix style-3"><div class="inner"><div data-filter="*" class="cbp-filter-item button-all" style="text-transform:capitalize;"><span>All</span><div class="cbp-filter-counter"></div></div><div data-filter=".marketing" class="cbp-filter-item" title="Logo" style="text-transform:capitalize;"><span>Logo</span><div class="cbp-filter-counter"></div></div><div data-filter=".ux-design" class="cbp-filter-item" title="Broucher Design" style="text-transform:capitalize;"><span>Broucher Design</span><div class="cbp-filter-counter"></div></div><div data-filter=".web-design" class="cbp-filter-item" title="Banner Design" style="text-transform:capitalize;"><span>Banner Design</span><div class="cbp-filter-counter"></div></div><div data-filter=".app" class="cbp-filter-item" title="Business Card Design" style="text-transform:capitalize;"><span>Business Card Design</span><div class="cbp-filter-counter"></div></div><div data-filter=".branding" class="cbp-filter-item" title="Branding" style="text-transform:capitalize;"><span>Branding</span><div class="cbp-filter-counter"></div></div></div></div>
                                                                        <div id="portfolio" class="cbp">

                                                                            <div class="cbp-item branding app home-portfolio">
                                                                                <div class="project-box style-2">
                                                                                    <div class="inner">
                                                                                        <div class="project-wrap"><div class="project-image"><div class="inner">
                                                                                                    <img width="370" height="260" src="<?php echo base_url(); ?>assets/front/wp-content/uploads/2019/09/portfolio-project1-370x260.jpg" class="attachment-ambersix-rectangle size-ambersix-rectangle wp-post-image" alt="" loading="lazy" /><div class="project-text"><div class="icons"><a href="/wp-content/uploads/2019/09/portfolio-project1.jpg" class="zoom popup-image"><span class="linea-basic-magnifier-plus"></span></a><a href="/project/masonry-project-08/" class="link"><span class="linea-basic-link"></span></a></div></div></div><h4 class="title"><a href="/project/masonry-project-08/" title="Minimal Illustration">Minimal Illustration</a></h4><div class="terms"><a class="branding" href="/project_category/branding/">Branding</a> / <a class="app" href="/project_category/app/">Business Card Design</a> / <a class="home-portfolio" href="/project_category/home-portfolio/">Home-Portfolio</a></div></div></div>		                </div>
                                                                                </div><!-- /.project-box -->
                                                                            </div><!-- /.cbp-item -->

                                                                            <div class="cbp-item ux-design app">
                                                                                <div class="project-box style-2">
                                                                                    <div class="inner">
                                                                                        <div class="project-wrap"><div class="project-image"><div class="inner"><img width="370" height="570" src="<?php echo base_url(); ?>assets/front/wp-content/uploads/2019/09/portfolio-project2.jpg" class="attachment-ambersix-rectangle2 size-ambersix-rectangle2 wp-post-image" alt="" loading="lazy" srcset="<?php echo base_url(); ?>assets/front/wp-content/uploads/2019/09/portfolio-project2.jpg 370w, <?php echo base_url(); ?>assets/front/wp-content/uploads/2019/09/portfolio-project2-195x300.jpg 195w" sizes="(max-width: 370px) 100vw, 370px" /><div class="project-text"><div class="icons"><a href="/wp-content/uploads/2019/09/portfolio-project2.jpg" class="zoom popup-image"><span class="linea-basic-magnifier-plus"></span></a><a href="/project/masonry-project-07/" class="link"><span class="linea-basic-link"></span></a></div></div></div><h4 class="title"><a href="/project/masonry-project-07/" title="Mobile App Design">Mobile App Design</a></h4><div class="terms"><a class="ux-design" href="/project_category/ux-design/">Broucher Design</a> / <a class="app" href="/project_category/app/">Business Card Design</a></div></div></div>		                </div>
                                                                                </div><!-- /.project-box -->
                                                                            </div><!-- /.cbp-item -->

                                                                            <div class="cbp-item app marketing">
                                                                                <div class="project-box style-2">
                                                                                    <div class="inner">
                                                                                        <div class="project-wrap"><div class="project-image"><div class="inner"><img width="370" height="260" src="<?php echo base_url(); ?>assets/front/wp-content/uploads/2019/09/portfolio-project3.jpg" class="attachment-ambersix-rectangle size-ambersix-rectangle wp-post-image" alt="" loading="lazy" srcset="<?php echo base_url(); ?>assets/front/wp-content/uploads/2019/09/portfolio-project3.jpg 370w, <?php echo base_url(); ?>assets/front/wp-content/uploads/2019/09/portfolio-project3-300x211.jpg 300w" sizes="(max-width: 370px) 100vw, 370px" /><div class="project-text"><div class="icons"><a href="/wp-content/uploads/2019/09/portfolio-project3.jpg" class="zoom popup-image"><span class="linea-basic-magnifier-plus"></span></a><a href="/project/masonry-project-06/" class="link"><span class="linea-basic-link"></span></a></div></div></div><h4 class="title"><a href="/project/masonry-project-06/" title="Professional Website">Professional Website</a></h4><div class="terms"><a class="app" href="/project_category/app/">Business Card Design</a> / <a class="marketing" href="/project_category/marketing/">Logo</a></div></div></div>		                </div>
                                                                                </div><!-- /.project-box -->
                                                                            </div><!-- /.cbp-item -->

                                                                            <div class="cbp-item branding app marketing">
                                                                                <div class="project-box style-2">
                                                                                    <div class="inner">
                                                                                        <div class="project-wrap"><div class="project-image"><div class="inner"><img width="370" height="570" src="<?php echo base_url(); ?>assets/front/wp-content/uploads/2019/09/portfolio-project4.jpg" class="attachment-ambersix-rectangle2 size-ambersix-rectangle2 wp-post-image" alt="" loading="lazy" srcset="<?php echo base_url(); ?>assets/front/wp-content/uploads/2019/09/portfolio-project4.jpg 370w, <?php echo base_url(); ?>assets/front/wp-content/uploads/2019/09/portfolio-project4-195x300.jpg 195w" sizes="(max-width: 370px) 100vw, 370px" /><div class="project-text"><div class="icons"><a href="/wp-content/uploads/2019/09/portfolio-project4.jpg" class="zoom popup-image"><span class="linea-basic-magnifier-plus"></span></a><a href="/project/masonry-project-05/" class="link"><span class="linea-basic-link"></span></a></div></div></div><h4 class="title"><a href="/project/masonry-project-05/" title="Fashion Animations">Fashion Animations</a></h4><div class="terms"><a class="branding" href="/project_category/branding/">Branding</a> / <a class="app" href="/project_category/app/">Business Card Design</a> / <a class="marketing" href="/project_category/marketing/">Logo</a></div></div></div>		                </div>
                                                                                </div><!-- /.project-box -->
                                                                            </div><!-- /.cbp-item -->

                                                                            <div class="cbp-item web-design branding">
                                                                                <div class="project-box style-2">
                                                                                    <div class="inner">
                                                                                        <div class="project-wrap"><div class="project-image"><div class="inner"><img width="370" height="570" src="<?php echo base_url(); ?>assets/front/wp-content/uploads/2019/09/portfolio-project6.jpg" class="attachment-ambersix-rectangle2 size-ambersix-rectangle2 wp-post-image" alt="" loading="lazy" srcset="<?php echo base_url(); ?>assets/front/wp-content/uploads/2019/09/portfolio-project6.jpg 370w, <?php echo base_url(); ?>assets/front/wp-content/uploads/2019/09/portfolio-project6-195x300.jpg 195w" sizes="(max-width: 370px) 100vw, 370px" /><div class="project-text"><div class="icons"><a href="/wp-content/uploads/2019/09/portfolio-project6.jpg" class="zoom popup-image"><span class="linea-basic-magnifier-plus"></span></a><a href="/project/masonry-project-04/" class="link"><span class="linea-basic-link"></span></a></div></div></div><h4 class="title"><a href="/project/masonry-project-04/" title="Business Illustration">Business Illustration</a></h4><div class="terms"><a class="web-design" href="/project_category/web-design/">Banner Design</a> / <a class="branding" href="/project_category/branding/">Branding</a></div></div></div>		                </div>
                                                                                </div><!-- /.project-box -->
                                                                            </div><!-- /.cbp-item -->

                                                                            <div class="cbp-item branding ux-design">
                                                                                <div class="project-box style-2">
                                                                                    <div class="inner">
                                                                                        <div class="project-wrap"><div class="project-image"><div class="inner"><img width="370" height="260" src="<?php echo base_url(); ?>assets/front/wp-content/uploads/2019/09/portfolio-project5.jpg" class="attachment-ambersix-rectangle size-ambersix-rectangle wp-post-image" alt="" loading="lazy" srcset="<?php echo base_url(); ?>assets/front/wp-content/uploads/2019/09/portfolio-project5.jpg 370w, <?php echo base_url(); ?>assets/front/wp-content/uploads/2019/09/portfolio-project5-300x211.jpg 300w" sizes="(max-width: 370px) 100vw, 370px" /><div class="project-text"><div class="icons"><a href="/wp-content/uploads/2019/09/portfolio-project5.jpg" class="zoom popup-image"><span class="linea-basic-magnifier-plus"></span></a><a href="/project/masonry-project-03/" class="link"><span class="linea-basic-link"></span></a></div></div></div><h4 class="title"><a href="/project/masonry-project-03/" title="Motion Design">Motion Design</a></h4><div class="terms"><a class="branding" href="/project_category/branding/">Branding</a> / <a class="ux-design" href="/project_category/ux-design/">Broucher Design</a></div></div></div>		                </div>
                                                                                </div><!-- /.project-box -->
                                                                            </div><!-- /.cbp-item -->
                                                                        </div><!-- /#portfolio -->



                                                                    </div>
                                                                </div><!-- /.ambersix-project -->


                                                                <div class="ambersix-spacer clearfix" data-desktop="120" data-mobi="60" data-smobi="60"></div></div></div></div></div></div></section></div>