 <div class="vc-custom-col-spacing clearfix vc-col-spacing-30"><section class="wpb_row vc_row-fluid"><div class="ambersix-container"><div class="row-inner clearfix"><div class="wpb_column vc_column_container vc_col-sm-12"><div class="vc_column-inner"><div class="wpb_wrapper">
                                                                <div class="ambersix-spacer clearfix" data-desktop="60" data-mobi="60" data-smobi="60"></div><div class="ambersix-content-box clearfix" ><div class="vc-custom-col-inner-spacing clearfix vc-col-inner-spacing-30"><div class="wpb_row vc_inner vc_row-fluid"><div class="wpb_column vc_column_container vc_col-sm-6"><div class="vc_column-inner"><div class="wpb_wrapper">
                                                                                        <div class="ambersix-spacer clearfix" data-desktop="30" data-mobi="30" data-smobi="30"></div><div class="ambersix-divider divider-left divider-solid" style="width:140px;border-width:2px;border-top-color:#ffada6;margin-bottom:33px;"></div><div class="clearfix"></div><div class="ambersix-content-box clearfix" data-padding="0 30px 0 0" data-mobipadding="0" data-margin="" data-mobimargin="" >
                                                                                            <div class="inner ctb-477885153" style="background-position:left top;background-repeat:no-repeat;"  data-background="">
                                                                                                <div class="ambersix-headings clearfix  wow fadeInUp" data-font=42 data-wow-duration="0.75s" data-wow-delay="0s"><h2 class="heading clearfix" style="line-height:50px;margin-bottom:25px;font-size:42px;">
                                                                                                        Your business is your logo, your logo is your business
                                                                                                    </h2><p class="sub-heading clearfix" style="font-style:normal;color:#222222;font-size:20px;line-height:24px;margin-bottom:30px;">
                                                                                                        Want that dream logo for your business?
                                                                                                    </p><div class="extra-content clearfix">
                                                                                                        <p>Want it to be the cream of the crop, the crème de la crème? Then you’ve come to the right place. Our online logo maker lets you generate logos perfectly suited to your business from a professionally designed library, instantly.</p>
                                                                                                        <p>You can customise the logos for free and make a logo you love in minutes &#8211; who doesn&#8217;t like the sound of that?</p>

                                                                                                    </div></div>
                                                                                            </div>
                                                                                        </div>
                                                                                        <div class="ambersix-spacer clearfix" data-desktop="18" data-mobi="18" data-smobi="18"></div><div><a class="ambersix-links  link-style-4 dark" href="https://ninzio.com/amber/portfolio/" >
                                                                                                <span class="text">VISIT OUR PROJECTS</span> <span class="line"></span>
                                                                                            </a></div></div></div></div><div class="wpb_column vc_column_container vc_col-sm-6"><div class="vc_column-inner"><div class="wpb_wrapper">
                                                                                        <div class="ambersix-parallax-box"><div class="ambersix-parallax-item" style="left:35%;top:50px;"><div class="20" style="box-shadow: 0px 0px 70px 0px rgba(0,0,0,0.15);" data-parallax='{"x" : 0, "y" : -50, "from-scroll" : 0, "smoothness" : 20}'><img src="<?php echo base_url(); ?>assets/front/wp-content/uploads/2019/09/about-parallax-img2.jpg" alt="image"></div></div><div class="ambersix-parallax-item" style="left:0px;top:290px;"><div class="0" style="box-shadow: 0px 0px 70px 0px rgba(0,0,0,0.15);" data-parallax='{"x" : 0, "y" : -100, "from-scroll" : 0, "smoothness" : 0}'><img src="<?php echo base_url(); ?>assets/front/wp-content/uploads/2019/09/about-parallax-img1.jpg" alt="image"></div></div></div></div></div></div></div></div></div>
                                                                <div class="ambersix-spacer clearfix" data-desktop="160" data-mobi="100" data-smobi="60"></div></div></div></div></div></div></section></div>